//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace TerrariaInvEdit.Properties
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources
    {

        private static ResourceManager resourceMan;

        private static CultureInfo resourceCulture;

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    ResourceManager temp = new ResourceManager("TerrariaInvEdit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap arrow_refresh
        {
            get
            {
                object obj = ResourceManager.GetObject("arrow_refresh", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap balloon_twitter
        {
            get
            {
                object obj = ResourceManager.GetObject("balloon_twitter", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Buff_0
        {
            get
            {
                object obj = ResourceManager.GetObject("Buff_0", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap cross
        {
            get
            {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Data
        {
            get
            {
                object obj = ResourceManager.GetObject("Data", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap disk_black
        {
            get
            {
                object obj = ResourceManager.GetObject("disk_black", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap disks_black
        {
            get
            {
                object obj = ResourceManager.GetObject("disks_black", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap drive_download
        {
            get
            {
                object obj = ResourceManager.GetObject("drive_download", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap folder_horizontal_open
        {
            get
            {
                object obj = ResourceManager.GetObject("folder_horizontal_open", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon icon
        {
            get
            {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap information
        {
            get
            {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap kdev
        {
            get
            {
                object obj = ResourceManager.GetObject("kdev", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap map_arrow
        {
            get
            {
                object obj = ResourceManager.GetObject("map_arrow", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap money_arrow
        {
            get
            {
                object obj = ResourceManager.GetObject("money_arrow", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap page_refresh
        {
            get
            {
                object obj = ResourceManager.GetObject("page_refresh", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Player_Eye_Whites
        {
            get
            {
                object obj = ResourceManager.GetObject("Player_Eye_Whites", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Player_Eyes
        {
            get
            {
                object obj = ResourceManager.GetObject("Player_Eyes", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Player_Hands
        {
            get
            {
                object obj = ResourceManager.GetObject("Player_Hands", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Player_Hands2
        {
            get
            {
                object obj = ResourceManager.GetObject("Player_Hands2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Player_Head
        {
            get
            {
                object obj = ResourceManager.GetObject("Player_Head", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Operation Failed!
        /// {0} the file is in use by another application..
        /// </summary>
        internal static string Player_NoOpFileInUse
        {
            get
            {
                return ResourceManager.GetString("Player_NoOpFileInUse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Operation Failed!
        /// {0} the file or path does not exist..
        /// </summary>
        internal static string Player_NoOpFileNoExist
        {
            get
            {
                return ResourceManager.GetString("Player_NoOpFileNoExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Player_Pants
        {
            get
            {
                object obj = ResourceManager.GetObject("Player_Pants", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Player_Shirt
        {
            get
            {
                object obj = ResourceManager.GetObject("Player_Shirt", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Player_Shoes
        {
            get
            {
                object obj = ResourceManager.GetObject("Player_Shoes", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Player_Undershirt
        {
            get
            {
                object obj = ResourceManager.GetObject("Player_Undershirt", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Player_Undershirt2
        {
            get
            {
                object obj = ResourceManager.GetObject("Player_Undershirt2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 4f2f3e66d8dd491fafe2a46560be4688.
        /// </summary>
        internal static string Rollbar_Access
        {
            get
            {
                return ResourceManager.GetString("Rollbar_Access", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap shoot
        {
            get
            {
                object obj = ResourceManager.GetObject("shoot", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap shootavy
        {
            get
            {
                object obj = ResourceManager.GetObject("shootavy", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Skin_Arm
        {
            get
            {
                object obj = ResourceManager.GetObject("Skin_Arm", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Skin_Body
        {
            get
            {
                object obj = ResourceManager.GetObject("Skin_Body", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Skin_Legs
        {
            get
            {
                object obj = ResourceManager.GetObject("Skin_Legs", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap user_arrow
        {
            get
            {
                object obj = ResourceManager.GetObject("user_arrow", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
    }
}
